Repository SeleniumHQ/seleniumhq.github.io, pull requests merged in 2024-11, with the labels that each got.

#2038 update remote_webdriver for Chinese version
  website_and_docs/content/documentation/webdriver/drivers/remote_webdriver.zh-cn.md
Labels: Review effort [1-5]: 3

#2039 docs: add Python code for Safari Technology Preview
  website_and_docs/content/documentation/webdriver/browsers/safari.en.md
  website_and_docs/content/documentation/webdriver/browsers/safari.ja.md
  website_and_docs/content/documentation/webdriver/browsers/safari.pt-br.md
  website_and_docs/content/documentation/webdriver/browsers/safari.zh-cn.md
Labels: Review effort [1-5]: 1

#2034 Corrected C# "Remote WebDriver / Download a File" example reference
  website_and_docs/content/documentation/webdriver/drivers/remote_webdriver.en.md
  website_and_docs/content/documentation/webdriver/drivers/remote_webdriver.ja.md
Labels: Review effort [1-5]: 1

#2040 [ci] Update script to fetch Nightly version for examples run
  .github/workflows/dotnet-examples.yml
  .github/workflows/java-examples.yml
  .github/workflows/js-examples.yml
  .github/workflows/python-examples.yml
  .github/workflows/ruby-examples.yml
  scripts/latest-nightly-version.ps1
  scripts/latest-nightly-version.py
  scripts/latest-nightly-version.sh
  scripts/latest-python-nightly-version.py
  scripts/requirements.txt
Labels: Review effort [1-5]: 3

#2041 Add examples for drivers http_client in java and python
  .github/workflows/java-examples.yml
  .github/workflows/python-examples.yml
  .gitignore
  examples/java/src/test/java/dev/selenium/BaseTest.java
  examples/java/src/test/java/dev/selenium/drivers/HttpClientTest.java
  examples/java/src/test/resources/server.jks
  examples/java/src/test/resources/tls.crt
  examples/java/src/test/resources/tls.key
  examples/python/requirements.txt
  examples/python/tests/actions_api/test_mouse.py
  examples/python/tests/bidi/cdp/test_script.py
  examples/python/tests/conftest.py
  examples/python/tests/drivers/test_http_client.py
  examples/python/tests/resources/server.jks
  examples/python/tests/resources/tls.crt
  examples/python/tests/resources/tls.key
  website_and_docs/content/documentation/webdriver/actions_api/mouse.en.md
  website_and_docs/content/documentation/webdriver/actions_api/mouse.ja.md
  website_and_docs/content/documentation/webdriver/actions_api/mouse.pt-br.md
  website_and_docs/content/documentation/webdriver/actions_api/mouse.zh-cn.md
  website_and_docs/content/documentation/webdriver/bidi/cdp/script.en.md
  website_and_docs/content/documentation/webdriver/bidi/cdp/script.ja.md
  website_and_docs/content/documentation/webdriver/bidi/cdp/script.pt-br.md
  website_and_docs/content/documentation/webdriver/bidi/cdp/script.zh-cn.md
  website_and_docs/content/documentation/webdriver/drivers/http_client.en.md
  website_and_docs/content/documentation/webdriver/drivers/http_client.ja.md
  website_and_docs/content/documentation/webdriver/drivers/http_client.pt-br.md
  website_and_docs/content/documentation/webdriver/drivers/http_client.zh-cn.md
Labels: Review effort [1-5]: 4

#2043 added java code for cookies
  examples/java/src/test/java/dev/selenium/interactions/CookiesTest.java
  website_and_docs/content/documentation/webdriver/interactions/cookies.en.md
  website_and_docs/content/documentation/webdriver/interactions/cookies.ja.md
  website_and_docs/content/documentation/webdriver/interactions/cookies.pt-br.md
  website_and_docs/content/documentation/webdriver/interactions/cookies.zh-cn.md
Labels: Review effort [1-5]: 3

#2044 Blog post for Selenium 4.26
  website_and_docs/content/blog/2024/selenium-4-26-released.md
  website_and_docs/layouts/partials/selenium-clients-and-webdriver-bindings.html
  website_and_docs/static/images/blog/2024/selenium_4.26.jpg
Labels: Review effort [1-5]: 2

#2045 Correct Webdriver HTTP Client in Python examples
  examples/python/tests/drivers/test_http_client.py
Labels: Review effort [1-5]: 2

#2047 fix python README.md for running tests
  examples/python/README.md
Labels: Review effort [1-5]: 1

#1991 Added se-config.toml Example to Selenium Manager
  examples/python/tests/selenium_manager/example_se-config.toml
  website_and_docs/content/documentation/selenium_manager.en.md
  website_and_docs/content/documentation/selenium_manager.ja.md
  website_and_docs/content/documentation/selenium_manager.pt-br.md
  website_and_docs/content/documentation/selenium_manager.zh-cn.md
Labels: documentation, Review effort [1-5]: 2

#2049 added csharp cookie code
  examples/dotnet/SeleniumDocs/Interactions/CookiesTest.cs
  website_and_docs/content/documentation/webdriver/interactions/cookies.en.md
  website_and_docs/content/documentation/webdriver/interactions/cookies.ja.md
  website_and_docs/content/documentation/webdriver/interactions/cookies.pt-br.md
  website_and_docs/content/documentation/webdriver/interactions/cookies.zh-cn.md
Labels: Review effort [1-5]: 3

#2048 [py]: Add firefox python full page screenshot example
  examples/python/tests/browsers/test_firefox.py
  website_and_docs/content/documentation/webdriver/browsers/firefox.en.md
  website_and_docs/content/documentation/webdriver/browsers/firefox.ja.md
  website_and_docs/content/documentation/webdriver/browsers/firefox.pt-br.md
  website_and_docs/content/documentation/webdriver/browsers/firefox.zh-cn.md
Labels: Review effort [1-5]: 2

#1981 Rephrase/reformat a few sentences
  website_and_docs/content/documentation/overview/details.en.md
  website_and_docs/content/documentation/webdriver/_index.en.md
  website_and_docs/content/documentation/webdriver/troubleshooting/_index.en.md
  website_and_docs/content/documentation/webdriver/troubleshooting/_index.pt-br.md
  website_and_docs/content/documentation/webdriver/troubleshooting/errors/_index.en.md
  website_and_docs/content/documentation/webdriver/troubleshooting/errors/_index.ja.md
  website_and_docs/content/documentation/webdriver/troubleshooting/errors/_index.pt-br.md
Labels: documentation, Review effort [1-5]: 1

#2050 [py]: add firefox context example for python
  examples/python/tests/browsers/test_firefox.py
  website_and_docs/content/documentation/webdriver/browsers/firefox.en.md
  website_and_docs/content/documentation/webdriver/browsers/firefox.ja.md
  website_and_docs/content/documentation/webdriver/browsers/firefox.pt-br.md
  website_and_docs/content/documentation/webdriver/browsers/firefox.zh-cn.md
Labels: Review effort [1-5]: 2

#2054 [py]: add chrome and edge network conditions example and docs
  examples/python/tests/browsers/test_chrome.py
  examples/python/tests/browsers/test_edge.py
  website_and_docs/content/documentation/webdriver/browsers/chrome.en.md
  website_and_docs/content/documentation/webdriver/browsers/chrome.ja.md
  website_and_docs/content/documentation/webdriver/browsers/chrome.pt-br.md
  website_and_docs/content/documentation/webdriver/browsers/chrome.zh-cn.md
  website_and_docs/content/documentation/webdriver/browsers/edge.en.md
  website_and_docs/content/documentation/webdriver/browsers/edge.ja.md
  website_and_docs/content/documentation/webdriver/browsers/edge.pt-br.md
  website_and_docs/content/documentation/webdriver/browsers/edge.zh-cn.md
Labels: Review effort [1-5]: 2

#2052 docs(zh-cn): update typo and finish translation of 'printing page'
  website_and_docs/content/documentation/webdriver/interactions/print_page.en.md
  website_and_docs/content/documentation/webdriver/interactions/print_page.ja.md
  website_and_docs/content/documentation/webdriver/interactions/print_page.pt-br.md
  website_and_docs/content/documentation/webdriver/interactions/print_page.zh-cn.md
Labels: Review effort [1-5]: 1

#2055 docs/selenium_manager: mention about Python now supporting ENV for driver path
  website_and_docs/content/documentation/selenium_manager.en.md
  website_and_docs/content/documentation/selenium_manager.ja.md
  website_and_docs/content/documentation/selenium_manager.pt-br.md
  website_and_docs/content/documentation/selenium_manager.zh-cn.md
Labels: Review effort [1-5]: 1

#2060 docs: update committers list
  website_and_docs/content/project/structure/_index.html
Labels: Review effort [1-5]: 1

#2057 [dotnet] Add page print example
  examples/dotnet/SeleniumDocs/Interactions/PrintOptionsTest.cs
  website_and_docs/content/documentation/webdriver/interactions/print_page.en.md
  website_and_docs/content/documentation/webdriver/interactions/print_page.ja.md
  website_and_docs/content/documentation/webdriver/interactions/print_page.pt-br.md
  website_and_docs/content/documentation/webdriver/interactions/print_page.zh-cn.md
Labels: Review effort [1-5]: 1

#2061 Showing OpenCollective sponsors
  website_and_docs/content/sponsors/_index.html
  website_and_docs/layouts/partials/open-collective-level-sponsors.html
  website_and_docs/layouts/sponsors/list.html
Labels: Review effort [1-5]: 2

#2062 Adding Boni to the TLC
  website_and_docs/content/project/structure/_index.html
Labels: Review effort [1-5]: 1

#2059 [java] add safari technlogy preview code snippet
  examples/java/src/test/java/dev/selenium/browsers/SafariTest.java
  website_and_docs/content/documentation/webdriver/browsers/safari.en.md
  website_and_docs/content/documentation/webdriver/browsers/safari.ja.md
  website_and_docs/content/documentation/webdriver/browsers/safari.pt-br.md
  website_and_docs/content/documentation/webdriver/browsers/safari.zh-cn.md
Labels: Review effort [1-5]: 1

#2058 [py]: add chrome and edge set_permissions docs
  examples/python/tests/browsers/test_chrome.py
  examples/python/tests/browsers/test_edge.py
  website_and_docs/content/documentation/webdriver/browsers/chrome.en.md
  website_and_docs/content/documentation/webdriver/browsers/chrome.ja.md
  website_and_docs/content/documentation/webdriver/browsers/chrome.pt-br.md
  website_and_docs/content/documentation/webdriver/browsers/chrome.zh-cn.md
  website_and_docs/content/documentation/webdriver/browsers/edge.en.md
  website_and_docs/content/documentation/webdriver/browsers/edge.ja.md
  website_and_docs/content/documentation/webdriver/browsers/edge.pt-br.md
  website_and_docs/content/documentation/webdriver/browsers/edge.zh-cn.md
Labels: Review effort [1-5]: 2

#2064 [ci] Get latest Nightly from TestPyPi sort by upload_time
  scripts/latest-python-nightly-version.py
Labels: Review effort [1-5]: 1

#2066 [java]: docs example for full page screenshot in firefox
  examples/java/src/test/java/dev/selenium/browsers/FirefoxTest.java
  website_and_docs/content/documentation/webdriver/browsers/firefox.en.md
  website_and_docs/content/documentation/webdriver/browsers/firefox.ja.md
  website_and_docs/content/documentation/webdriver/browsers/firefox.pt-br.md
  website_and_docs/content/documentation/webdriver/browsers/firefox.zh-cn.md
Labels: Review effort [1-5]: 1

#2067 [py] document console output for Edge
  website_and_docs/content/documentation/webdriver/browsers/edge.en.md
  website_and_docs/content/documentation/webdriver/browsers/edge.ja.md
  website_and_docs/content/documentation/webdriver/browsers/edge.pt-br.md
  website_and_docs/content/documentation/webdriver/browsers/edge.zh-cn.md
Labels: Review effort [1-5]: 1

#2068 [java]: docs for set context in firefox
  examples/java/src/test/java/dev/selenium/browsers/FirefoxTest.java
  website_and_docs/content/documentation/webdriver/browsers/firefox.en.md
  website_and_docs/content/documentation/webdriver/browsers/firefox.ja.md
  website_and_docs/content/documentation/webdriver/browsers/firefox.pt-br.md
  website_and_docs/content/documentation/webdriver/browsers/firefox.zh-cn.md
Labels: Review effort [1-5]: 2

#2072 [py]: add example and docs for casting in edge and chrome
  examples/python/tests/browsers/test_chrome.py
  examples/python/tests/browsers/test_edge.py
  website_and_docs/content/documentation/webdriver/browsers/chrome.en.md
  website_and_docs/content/documentation/webdriver/browsers/chrome.ja.md
  website_and_docs/content/documentation/webdriver/browsers/chrome.pt-br.md
  website_and_docs/content/documentation/webdriver/browsers/chrome.zh-cn.md
  website_and_docs/content/documentation/webdriver/browsers/edge.en.md
  website_and_docs/content/documentation/webdriver/browsers/edge.ja.md
  website_and_docs/content/documentation/webdriver/browsers/edge.pt-br.md
  website_and_docs/content/documentation/webdriver/browsers/edge.zh-cn.md
Labels: Review effort [1-5]: 2

#2071 [java]: add docs and example for setNetworkConditions
  examples/java/src/test/java/dev/selenium/browsers/ChromeTest.java
  examples/java/src/test/java/dev/selenium/browsers/EdgeTest.java
  website_and_docs/content/documentation/webdriver/browsers/chrome.en.md
  website_and_docs/content/documentation/webdriver/browsers/chrome.ja.md
  website_and_docs/content/documentation/webdriver/browsers/chrome.pt-br.md
  website_and_docs/content/documentation/webdriver/browsers/chrome.zh-cn.md
  website_and_docs/content/documentation/webdriver/browsers/edge.en.md
  website_and_docs/content/documentation/webdriver/browsers/edge.ja.md
  website_and_docs/content/documentation/webdriver/browsers/edge.pt-br.md
  website_and_docs/content/documentation/webdriver/browsers/edge.zh-cn.md
Labels: Review effort [1-5]: 2

#2079 Bump versions to 4.27.0
  examples/dotnet/SeleniumDocs/BaseTest.cs
  examples/java/build.gradle
  examples/java/src/test/java/dev/selenium/bidi/cdp/CdpApiTest.java
  examples/java/src/test/java/dev/selenium/bidi/cdp/NetworkTest.java
  examples/python/tests/bidi/cdp/test_network.py
  examples/python/tests/conftest.py
  examples/ruby/Gemfile
  examples/ruby/Gemfile.lock
  website_and_docs/layouts/downloads/list.html
  website_and_docs/layouts/partials/selenium-clients-and-webdriver-bindings.html
Labels: Review effort [1-5]: 1

#2074 [py]: add docs for `get_log` for chrome and edge
  examples/python/tests/browsers/test_chrome.py
  examples/python/tests/browsers/test_edge.py
  website_and_docs/content/documentation/webdriver/browsers/chrome.en.md
  website_and_docs/content/documentation/webdriver/browsers/chrome.ja.md
  website_and_docs/content/documentation/webdriver/browsers/chrome.pt-br.md
  website_and_docs/content/documentation/webdriver/browsers/chrome.zh-cn.md
  website_and_docs/content/documentation/webdriver/browsers/edge.en.md
  website_and_docs/content/documentation/webdriver/browsers/edge.ja.md
  website_and_docs/content/documentation/webdriver/browsers/edge.pt-br.md
  website_and_docs/content/documentation/webdriver/browsers/edge.zh-cn.md
Labels: Review effort [1-5]: 2

#2081 [py] fix line number
  website_and_docs/content/documentation/webdriver/drivers/_index.en.md
  website_and_docs/content/documentation/webdriver/drivers/_index.ja.md
  website_and_docs/content/documentation/webdriver/drivers/_index.pt-br.md
  website_and_docs/content/documentation/webdriver/drivers/_index.zh-cn.md
Labels: Review effort [1-5]: 1

#2086 Release 4.27
  website_and_docs/content/blog/2024/selenium-4-27-released.md
  website_and_docs/static/images/blog/2024/selenium_4.27.webp
Labels: Review effort [1-5]: 1

#2085 [py] move interactions code to code examples
  examples/python/tests/elements/test_interaction.py
  website_and_docs/content/documentation/webdriver/elements/interactions.en.md
  website_and_docs/content/documentation/webdriver/elements/interactions.ja.md
  website_and_docs/content/documentation/webdriver/elements/interactions.pt-br.md
  website_and_docs/content/documentation/webdriver/elements/interactions.zh-cn.md
Labels: Review effort [1-5]: 2

#2083 [java]: add docs for retrieving logs in chrome and edge
  examples/java/src/test/java/dev/selenium/browsers/ChromeTest.java
  examples/java/src/test/java/dev/selenium/browsers/EdgeTest.java
  examples/python/tests/browsers/test_chrome.py
  examples/python/tests/browsers/test_edge.py
  website_and_docs/content/documentation/webdriver/browsers/chrome.en.md
  website_and_docs/content/documentation/webdriver/browsers/chrome.ja.md
  website_and_docs/content/documentation/webdriver/browsers/chrome.pt-br.md
  website_and_docs/content/documentation/webdriver/browsers/chrome.zh-cn.md
  website_and_docs/content/documentation/webdriver/browsers/edge.en.md
  website_and_docs/content/documentation/webdriver/browsers/edge.ja.md
  website_and_docs/content/documentation/webdriver/browsers/edge.pt-br.md
  website_and_docs/content/documentation/webdriver/browsers/edge.zh-cn.md
Labels: Review effort [1-5]: 2

#2088 chore: add `text=true` to the broken code examples
  website_and_docs/content/documentation/webdriver/elements/interactions.en.md
  website_and_docs/content/documentation/webdriver/elements/interactions.ja.md
  website_and_docs/content/documentation/webdriver/elements/interactions.pt-br.md
  website_and_docs/content/documentation/webdriver/elements/interactions.zh-cn.md
  website_and_docs/content/documentation/webdriver/interactions/cookies.en.md
  website_and_docs/content/documentation/webdriver/interactions/cookies.ja.md
  website_and_docs/content/documentation/webdriver/interactions/cookies.pt-br.md
  website_and_docs/content/documentation/webdriver/interactions/cookies.zh-cn.md
Labels: Review effort [1-5]: 1
