Repository SeleniumHQ/seleniumhq.github.io, pull requests merged in 2025-05, with the labels that each got.

#1971 Added ElementNotVisibleException to Error Documentation
  website_and_docs/content/documentation/webdriver/troubleshooting/errors/_index.en.md
  website_and_docs/content/documentation/webdriver/troubleshooting/errors/_index.ja.md
  website_and_docs/content/documentation/webdriver/troubleshooting/errors/_index.pt-br.md
  website_and_docs/content/documentation/webdriver/troubleshooting/errors/_index.zh-cn.md
Labels: documentation, Review effort [1-5]: 2

#1967 Added CSharp Example to Selenium Manager
  examples/dotnet/SeleniumDocs/SeleniumManager/UsageTest.cs
  website_and_docs/content/documentation/selenium_manager.en.md
  website_and_docs/content/documentation/selenium_manager.ja.md
  website_and_docs/content/documentation/selenium_manager.pt-br.md
  website_and_docs/content/documentation/selenium_manager.zh-cn.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#1969 Added Ruby Example to Selenium Manager
  examples/ruby/spec/selenium_manager/usage.rb
  website_and_docs/content/documentation/selenium_manager.en.md
  website_and_docs/content/documentation/selenium_manager.ja.md
  website_and_docs/content/documentation/selenium_manager.pt-br.md
  website_and_docs/content/documentation/selenium_manager.zh-cn.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#1968 Added Javascript Example to Selenium Manager
  examples/javascript/test/selenium_manager/usage.spec.js
  website_and_docs/content/documentation/selenium_manager.en.md
  website_and_docs/content/documentation/selenium_manager.ja.md
  website_and_docs/content/documentation/selenium_manager.pt-br.md
  website_and_docs/content/documentation/selenium_manager.zh-cn.md
Labels: documentation, tests, Review effort [1-5]: 2

#2297 [rb] Linting Updates
  examples/ruby/spec/bidi/logging_spec.rb
  examples/ruby/spec/browsers/chrome_spec.rb
  examples/ruby/spec/browsers/edge_spec.rb
  examples/ruby/spec/browsers/safari_spec.rb
  examples/ruby/spec/drivers/http_client_spec.rb
  examples/ruby/spec/hello/hello_selenium.rb
  examples/ruby/spec/interactions/browser_spec.rb
  examples/ruby/spec/interactions/navigation_spec.rb
Labels: Review effort 1/5

#2299 Post for already released 4.30 and 4.31
  scripts/release-updates.sh
  website_and_docs/content/blog/2025/selenium-4-29-released.md
  website_and_docs/content/blog/2025/selenium-4-30-released.md
  website_and_docs/content/blog/2025/selenium-4-31-released.md
  website_and_docs/static/images/blog/2025/selenium_4.30.jpg
  website_and_docs/static/images/blog/2025/selenium_4.31.jpg
Labels: Review effort 2/5

#2300 Blog post 4 32
  website_and_docs/content/blog/2025/selenium-4-32-released.md
  website_and_docs/layouts/downloads/list.html
  website_and_docs/layouts/partials/selenium-clients-and-webdriver-bindings.html
  website_and_docs/static/images/blog/2025/selenium_4.32.jpg
Labels: Review effort 2/5

#1924 petesong/Add a Python example for the test practice
  README.md
  examples/python/tests/design_strategy/using_best_practice.py
  website_and_docs/content/documentation/test_practices/design_strategies.en.md
  website_and_docs/content/documentation/test_practices/design_strategies.ja.md
  website_and_docs/content/documentation/test_practices/design_strategies.pt-br.md
  website_and_docs/content/documentation/test_practices/design_strategies.zh-cn.md
Labels: documentation, tests, Review effort [1-5]: 4

#2303 added cookie ruby file
  examples/ruby/spec/interactions/cookies_spec.rb
Labels: Review effort 2/5

#2306 added ruby code in document
  examples/ruby/spec/interactions/cookies_spec.rb
  website_and_docs/content/documentation/webdriver/interactions/cookies.en.md
  website_and_docs/content/documentation/webdriver/interactions/cookies.ja.md
  website_and_docs/content/documentation/webdriver/interactions/cookies.pt-br.md
  website_and_docs/content/documentation/webdriver/interactions/cookies.zh-cn.md
Labels: Review effort 2/5

#2313 docs: Update toml Doc for zh-cn
  website_and_docs/content/documentation/grid/applicability.zh-cn.md
  website_and_docs/content/documentation/grid/components.zh-cn.md
  website_and_docs/content/documentation/grid/configuration/toml_options.zh-cn.md
Labels: Review effort 1/5

#2314 [deploy site] removing banner
  website_and_docs/hugo.toml
Labels: Review effort 1/5
