Repository SeleniumHQ/seleniumhq.github.io, pull requests merged in 2025-08, with the labels that each got.

#2408 [deploy site] blog for selenium community live
  website_and_docs/content/blog/2025/selenium-community-live-episode8.md
Labels: Review effort 2/5

#2412 updated youtube channel link
  website_and_docs/content/blog/2024/selenium-community-live-episode1.md
  website_and_docs/content/blog/2025/selenium-community-live-episode2.md
  website_and_docs/content/blog/2025/selenium-community-live-episode4.md
  website_and_docs/content/blog/2025/selenium-community-live-episode5.md
  website_and_docs/content/blog/2025/selenium-community-live-episode6.md
  website_and_docs/content/blog/2025/selenium-community-live-episode7.md
Labels: Review effort 1/5

#2413 docs: translate pen and mouse as Chinese
  website_and_docs/content/documentation/webdriver/actions_api/mouse.zh-cn.md
  website_and_docs/content/documentation/webdriver/actions_api/pen.zh-cn.md
Labels: Review effort 2/5

#1900 Moved alert/prompts and confirmations examples of Java tab to example sections and updated the …
  examples/java/src/test/java/dev/selenium/interactions/AlertsTest.java
  website_and_docs/content/documentation/webdriver/interactions/alerts.en.md
  website_and_docs/content/documentation/webdriver/interactions/alerts.ja.md
  website_and_docs/content/documentation/webdriver/interactions/alerts.pt-br.md
  website_and_docs/content/documentation/webdriver/interactions/alerts.zh-cn.md
Labels: documentation, tests, Review effort [1-5]: 3

#2424 Updating PLC members.
  website_and_docs/content/project/structure/_index.html
Labels: Review effort 1/5

#1889 Fix typos in two files
  examples/java/src/test/java/dev/selenium/elements/InformationTest.java
  examples/java/src/test/java/dev/selenium/elements/InteractionTest.java
Labels: enhancement, Review effort [1-5]: 2

#2277 Translation of contributing into Ja and fix typo error
  website_and_docs/content/documentation/about/contributing.en.md
  website_and_docs/content/documentation/about/contributing.ja.md
  website_and_docs/content/documentation/about/contributing.pt-br.md
  website_and_docs/content/documentation/about/contributing.zh-cn.md
Labels: Review effort 2/5

#2428 chore: fix typos
  website_and_docs/content/documentation/legacy/desired_capabilities.en.md
  website_and_docs/content/documentation/legacy/json_wire_protocol.en.md
  website_and_docs/content/documentation/selenium_manager.en.md
  website_and_docs/content/documentation/selenium_manager.ja.md
  website_and_docs/content/documentation/selenium_manager.pt-br.md
Labels: Review effort 1/5

#2438 Fix Release tag URLs in 2025 blog posts, like "selenium-4.30.0"
  website_and_docs/content/blog/2025/selenium-4-28-released.md
  website_and_docs/content/blog/2025/selenium-4-29-released.md
  website_and_docs/content/blog/2025/selenium-4-30-released.md
  website_and_docs/content/blog/2025/selenium-4-31-released.md
  website_and_docs/content/blog/2025/selenium-4-32-released.md
Labels: Review effort 1/5

#2439 Hugo Config option for blog URLs: avoid deprecation
  .github/workflows/deploy.yml
  .github/workflows/link-check.yml
  .github/workflows/test.yml
  .gitpod.yml
  README.md
  netlify.toml
  website_and_docs/content/documentation/about/contributing.en.md
  website_and_docs/content/documentation/about/contributing.ja.md
  website_and_docs/content/documentation/about/contributing.pt-br.md
  website_and_docs/content/documentation/about/contributing.zh-cn.md
  website_and_docs/hugo.toml
  website_and_docs/layouts/partials/previous-releases.html
  website_and_docs/layouts/shortcodes/gh-codeblock.html
  website_and_docs/layouts/shortcodes/gh-contributors.html
  website_and_docs/layouts/shortcodes/gh-user.html
Labels: Review effort 1/5

#2453 Updated Blog for the Community event 1
  website_and_docs/content/blog/2024/selenium-community-live-episode1.md
Labels: Review effort 2/5
