Repository SeleniumHQ/seleniumhq.github.io, pull requests merged in 2025-07, with the labels that each got.

#2367 Added Blog for Selenium Community Event 7
  website_and_docs/content/blog/2025/selenium-community-live-episode7.md
Labels: Review effort 2/5

#2368 [deploy site] added event information
  website_and_docs/hugo.toml
  website_and_docs/layouts/partials/announcement-banner.html
Labels: Review effort 1/5

#2377 Fix curl command name, syntax, and url
  website_and_docs/content/documentation/grid/advanced_features/endpoints.en.md
  website_and_docs/content/documentation/grid/advanced_features/endpoints.ja.md
  website_and_docs/content/documentation/grid/advanced_features/endpoints.pt-br.md
  website_and_docs/content/documentation/grid/advanced_features/endpoints.zh-cn.md
  website_and_docs/content/documentation/test_practices/discouraged/file_downloads.en.md
  website_and_docs/content/documentation/test_practices/discouraged/file_downloads.ja.md
  website_and_docs/content/documentation/test_practices/discouraged/file_downloads.pt-br.md
  website_and_docs/content/documentation/test_practices/discouraged/file_downloads.zh-cn.md
  website_and_docs/content/documentation/test_practices/discouraged/link_spidering.en.md
  website_and_docs/content/documentation/test_practices/discouraged/link_spidering.ja.md
  website_and_docs/content/documentation/test_practices/discouraged/link_spidering.pt-br.md
  website_and_docs/content/documentation/test_practices/discouraged/link_spidering.zh-cn.md
Labels: Review effort 1/5

#2378 Modified text of previous conference and added conf archive website link which was created by Diego
  website_and_docs/content/events/_index.html
Labels: Review effort 2/5

#2380 [deploy site] modified community youtube link
  website_and_docs/hugo.toml
Labels: Review effort 1/5

#2383 Release 4.34
  website_and_docs/content/blog/2025/selenium-4-34-released.md
  website_and_docs/layouts/partials/selenium-clients-and-webdriver-bindings.html
  website_and_docs/static/images/blog/2025/selenium_4.34.jpg
Labels: Review effort 2/5

#2391 [deploy site] added ruby raider project, modified links
  website_and_docs/content/ecosystem/_index.html
Labels: Review effort 2/5

#2392 Fix ecosystem pal
  website_and_docs/content/ecosystem/_index.html
Labels: Review effort 2/5

#2396 [deploy site] fixed link, added AI solutions
  website_and_docs/content/ecosystem/_index.html
Labels: Review effort 2/5

#2399 [deploy site] left sample annoucement information to guide new people…
  website_and_docs/layouts/partials/announcement-banner.html
Labels: Review effort 2/5, Possible security concern
